[[main]]
none = "none"

[[main]]
name = "Resume"
pageRef = "resume.md"

[[main]]
name = "Who I work with"
pageRef = "who.md"
identifier="whoIWorkWith"
weight = 1 

[[main]]
name = "Traction Stage"
parent = "whoIWorkWith"
pageRef = "traction.md"
weight = 1

[[main]]
name = "Growth Stage"
parent = "whoIWorkWith"
pageRef = "growth.md"
weight = 2

[[main]]
name = "Scale Stage"
parent = "whoIWorkWith"
pageRef = "scale.md"
weight = 2

[[main]]
name = "About Me"
pageRef = "about.md"
identifier = "aboutMe"
weight = 3 

[[main]]
name = "Introduction"
pageRef = "about.md"
parent = "aboutMe"

[[main]]
name = "Resume"
pageRef = "resume.md"
parent = "aboutMe"

[[footer]]
none = "none"
